name: Add an item
description: Add an entry to the a11yhood assistive technology dataset
title: "[New]: "
labels: 
- new
- assistive-technology
projects: 
- a11yhood/2
assignees:
  - tonyfast
  - jmankoff
body:
  - type: input
    attributes:
      label: url
      description: submit a url that has information about assistive technology.
    validations:
      required: true
  - type: markdown
    attributes:
      value: add an optional description about the submission you are making
  - type: textarea
    attributes:
      label: related urls 
      description: add a line separated list of other urls relevent to this item
    
